name: Get data from next voting minute
on:
  schedule:
    - cron: "0 0 * * 1" # Runs at midnight every Monday

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  workflow_call:
    inputs:
      target-repository:
        required: false
        type: string
        default: "codeforboston/boston-liquor-license-tracker"
      target-ref:
        required: false
        type: string
        default: "main"

# Sets the GITHUB_TOKEN permissions to allow committing changes, so we can update the next meeting date
permissions:
  contents: write
  pull-requests: write

jobs:
  check-pdf:
    outputs:
      pdf-found: ${{ steps.check.outputs.pdf-found }}
      pdf-file: ${{ steps.check.outputs.pdf-file }}
      voting-date: ${{ steps.check.outputs.voting-date }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.target-repository }}
          ref: ${{ inputs.target-ref }}

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
          cache-dependency-path: scripts/package-lock.json
      
      - name: Install dependencies
        working-directory: ./scripts
        run: npm ci 

      - name: Compile get voting minutes
        working-directory: ./scripts
        run: npm run build:get-voting-minutes

      - name: Run get voting minutes
        id: check
        working-directory: ./scripts
        run: |
          OUTPUT=$(npm run run:get-voting-minutes 2>&1 | tee /dev/stderr)
          SEL_OUTPUT=$(echo "$OUTPUT" | grep "::JSON_OUTPUT::" | sed 's/::JSON_OUTPUT:://')
          SUCCESS=$(echo "$SEL_OUTPUT" | jq -r '.success')
          if [ "$SUCCESS" != "true" ]; then
            echo "Script failed : $(echo "$SEL_OUTPUT" | jq -r '.message')"
            exit 1 
          fi

          PDF_FILE=$(echo "$SEL_OUTPUT" | jq -r '.fileName')
          VOTING_DATE=$(echo "$SEL_OUTPUT" | jq -r '.pdfDate')

          # Exit early if no new PDF to process
          if [ "$PDF_FILE" = "null" ] || [ "$VOTING_DATE" = "null" ]; then
            echo "pdf-found=false" >> $GITHUB_OUTPUT
          else
            echo "pdf-found=true" >> $GITHUB_OUTPUT
            echo "pdf-file=$PDF_FILE" >> $GITHUB_OUTPUT
            echo "voting-date=$VOTING_DATE" >> $GITHUB_OUTPUT
          fi
    
      - name: Upload voting PDF
        uses: actions/upload-artifact@v4
        if: steps.check.outputs.pdf-found == 'true'
        with:
          name: voting-pdf 
          path: ./scripts/${{ steps.check.outputs.pdf-file }}
          if-no-files-found: error
          retention-days: 2
    
  
  process-pdf:
    needs: check-pdf 
    if: needs.check-pdf.outputs.pdf-found == 'true'
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: ${{ inputs.target-repository }}
          ref: ${{ inputs.target-ref }}
          lfs: true

      - name: Setup python 
        uses: actions/setup-python@v5
        with: 
          python-version: '3.13'
          cache: 'pip'
        
      - name: Install Python dependencies
        working-directory: ./scripts
        run: pip install -r requirements.txt
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "npm"
          cache-dependency-path: scripts/package-lock.json
      
      - name: Install dependencies
        working-directory: ./scripts
        run: npm ci 
      
        # needs.check-pdf.outputs.pdf-file is just the filename,
        # so we need to download the artifact
      - name: Download voting pdf
        uses: actions/download-artifact@v5
        with: 
          name: voting-pdf 
          path: ./scripts

      - name: Run python script 
        working-directory: ./scripts
        run: |
          echo "PDF file: ${{ needs.check-pdf.outputs.pdf-file }}" 
          python3 extract_entity.py "${{ needs.check-pdf.outputs.pdf-file }}"
      
      - name: Compile update processed date 
        working-directory: ./scripts
        run: npm run build:update-last-processed

      - name: Run update processed date 
        working-directory: ./scripts 
        run: npm run run:update-last-processed -- ${{ needs.check-pdf.outputs.voting-date }}

        # Move pdf to long-term storage for the PR
      - name: Move PDF to data directory
        run: |
          mkdir -p ./client/src/data/voting-minutes
          mv ./scripts/${{ needs.check-pdf.outputs.pdf-file }} ./client/src/data/voting-minutes/
      
      - name: Create pull request to merge in new next meeting date
        uses: peter-evans/create-pull-request@v7
        with:
          title: "[SCRIPT] Update liquor license applicant data"
          body: |
            This PR updates the parsed liquor license applicant data.
            - Data extracted from the latest PDF downloaded by the workflow.
            - Auto-generated by the Liquor License Data GitHub Action.
          branch: update-liquor-license-data
          delete-branch: true
          commit-message: "[SCRIPT] Update liquor license applicant data"
          committer: Github Actions <hello@codeforboston.org>
          author: Github Actions <hello@codeforboston.org>
          add-paths: |
            client/src/data/last_processed_date.json
            client/src/data/licenses.json
            client/src/data/voting-minutes/${{ needs.check-pdf.outputs.pdf-file }}
